/**
 * Application Device Log (for GPS Tracking)
 * - request_id : Request ID generated by Device to connect api_device_log with app_device_log (GPS Tracking)
 * - device_utc : UTC Time on Device
 * - device_datetime : convert device_utc into yyyymmddHHMMSS
 * - server_received_datetime : datetime server receive the data
 */
CREATE TABLE xtimo_app_device_log
(
  xtimo_app_device_log_id bigint NOT NULL AUTO_INCREMENT,
  xtimo_device_app_id bigint NOT NULL,
  request_id varchar(100) NOT NULL,
  device_utc bigint NOT NULL,
  device_datetime varchar (14) NOT NULL,
  server_received_datetime varchar(14) NOT NULL,
  
  -- data GPS
  longitude double NOT NULL,
  latitude double NOT NULL,
  altitude double NOT NULL,
  accuracy double NOT NULL,
  speed double NOT NULL,
  
  -- data CGI
  mcc int NOT NULL,
  mnc int NOT NULL,
  lac int NOT NULL,
  cellid int NOT NULL,
  
  -- data Device
  device_signal double NOT NULL,
  batt_level double NOT NULL,
  batt_volt double NOT NULL,
  batt_temp double NOT NULL,
  imei varchar(100) NOT NULL,
  
  version bigint NOT NULL,
  primary key (xtimo_app_device_log_id)
);

--CREATE UNIQUE INDEX xtimo_app_device_log_index_01
--	ON xtimo_app_device_log
--	(xtimo_device_app_id, request_id);